trigger:
  - main
  - develop
  - stage
  - release*
  - feature*

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/azure-pipeline-templates

extends:
  template: pipeline-fe-library.yaml@templates
  parameters:
    libraryName: 'cp-virava-angular-helper'
    installCommand: 'npm install --force'
